### PR TITLE
Ported threshold detection agent to modular VOLTTRON

### PR DESCRIPTION
**Pull request by riley206-pnnl**
ported threshold detection to modular

### CODE REVIEW

**Comment by schandrika** [comment]
add conftest.py to tests folder and add src directory to path so that imports don't fail

**Comment by schandrika** [comment]
test_threshold_detection.py - which env did you run this in? 
the utility method is_running_in_container() throws exception for me. I am running in docker container.

**Comment by schandrika** [comment]
missing docs - please add docs

**Comment by riley206-pnnl** [comment]
> test_threshold_detection.py - which env did you run this in? the utility method is_running_in_container() throws exception for me. I am running in docker container.

I believe I ran this in poetry env

**Comment by schandrika** [comment]
Clean up unused imports.
Add docs folder and index.rst

**Comment by schandrika** [comment]
These tests fail for me
================================================= short test summary info ==================================================
FAILED tests/test_threshold_detection.py::test_below_min[volttron_instance0] - assert False
FAILED tests/test_threshold_detection.py::test_update_config[volttron_instance0] - assert False
FAILED tests/test_threshold_detection.py::test_device_publish[volttron_instance0] - assert False

**Pull request merged**
